const config = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 100],
    'footer-max-line-length': [2, 'always', 100],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'app',
        'web',
        'api',
        'ui',
        'auth',
        'design-system',
        'deps',
        'release',
        'config',
        'docs',
        'tests',
        'mocks',
        'ci',
        'github-actions',
        'styles',
        'scripts',
        'package',
        'env',
      ],
    ],
  },
}

export default config
